defaultSemverRangePrefix: ""

enableGlobalCache: true

enableScripts: false

enableColors: false

enableTelemetry: false

globalFolder: bin/yarn

plugins:
  - path: bin/yarn/plugins/@yarnpkg/plugin-licenses.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-licenses/v0.6.0/bundles/@yarnpkg/plugin-licenses.js"

yarnPath: bin/yarn/releases/yarn-2.4.3.cjs

